### ISSUE TITLE
Problem with Gufw

### ISSUE THREAD

**Issue by DUNNN3** [arcolinux/arcolinux-xfce#1]
Gufw is not working. Sorry, I know this is not a new issue; I watched K. Dubois's YouTube video about how one could fix the Gufw problem via nano by going into some script and changing /bin/ to /sbin/.  I followed the YouTube instructions, but still Gufw is not working. So, I'm reporting this as a bug.  I'm new to Arch based Linux distros. Probably most of you would consider me a newbie.

On Github I'm DUNNN3
On the Forum I'm Hoper (typo)
On Discord I'm hop

**Comment by arcolinuxz** [comment]
already fixed

Solved here
https://arcolinuxforum.com/viewtopic.php?f=29&t=2475&p=10022#p10022
